/**
 * Page assembly: frontmatter plus a serialized body, verified before it is
 * ever handed to the emitter.
 *
 * Frontmatter is a closed key set with JSON-encoded scalar values. YAML 1.2 is
 * a JSON superset, so `JSON.stringify` of a string is always a valid
 * double-quoted YAML scalar — that is the whole escaping story for the header,
 * and it means an evidence string can never terminate the block or introduce a
 * key.
 *
 * The generated-file marker is a YAML COMMENT inside that block, not an HTML
 * comment in the body: MDX has no `<!-- -->` comment syntax, so a body marker
 * would be a parse error, and a frontmatter KEY would surface in page metadata.
 */

import { fail } from "./errors.ts";
import { assertMdxSafe, serializeBody } from "./mdx.ts";
import type { SafeText } from "./text.ts";
import type { RootContent } from "mdast";

/**
 * Marker every generated page carries. The emitter refuses to delete a file
 * under its owned tree that does not carry it, so a stray hand-authored file
 * is reported rather than destroyed.
 */
export const GENERATED_MARKER =
  "# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`";

export type PageFrontmatter = {
  readonly title: SafeText;
  readonly description: SafeText;
  /** Sidebar ordering within its directory. */
  readonly sidebarPosition: number;
};

export type GeneratedPage = {
  /** POSIX-style path relative to the generated root, e.g. `records/al8860mp-13/index.mdx`. */
  readonly relativePath: string;
  readonly contents: string;
};

const RELATIVE_PATH_PATTERN = /^(?:[a-z0-9][a-z0-9-]*\/)*[a-z0-9][a-z0-9-]*\.mdx$/u;

export function buildPage(
  relativePath: string,
  frontmatter: PageFrontmatter,
  body: readonly RootContent[],
): GeneratedPage {
  if (!RELATIVE_PATH_PATTERN.test(relativePath)) {
    fail("PATH_CONTAINMENT", `generated path ${relativePath} is not a permitted shape`, {
      relativePath,
    });
  }
  if (!Number.isInteger(frontmatter.sidebarPosition) || frontmatter.sidebarPosition < 0) {
    fail("UNSAFE_VALUE", "sidebar_position must be a non-negative integer", {
      relativePath,
      value: String(frontmatter.sidebarPosition),
    });
  }

  const serialized = serializeBody(body);
  assertMdxSafe(serialized, relativePath);

  const header = [
    "---",
    GENERATED_MARKER,
    `title: ${JSON.stringify(frontmatter.title)}`,
    `description: ${JSON.stringify(frontmatter.description)}`,
    `sidebar_position: ${frontmatter.sidebarPosition}`,
    "---",
  ].join("\n");

  return { relativePath, contents: `${header}\n\n${serialized}` };
}

/** Whether a file on disk is one this generator owns. */
export function isGeneratedContents(contents: string): boolean {
  return contents.startsWith(`---\n${GENERATED_MARKER}\n`);
}
